#!/bin/bash

cd /opt/
wget http://h2o-release.s3.amazonaws.com/h2o/master/5153/h2o-3.31.0.5153.zip   
unzip h2o-3.31.0.5153.zip
mv /opt/h2o-3.31.0.5153 /opt/h2o
rm /opt/h2o-3.31.0.5153.zip
chmod -R 755 /opt/h2o && chown -R ubuntu:ubuntu /opt/h2o
