#!/bin/bash
#DO NOT UPGRADE, 2.24.0.5 has X-Frame-Options header that prevents us from displaying h2o in iframe
#^Not sure about this, but perhaps it's a typo and means 3.24.0.5
#updating the version to the latest to test out
cd /opt/
wget https://h2o-release.s3.amazonaws.com/h2o/rel-yu/1/h2o-3.28.0.1.zip   
unzip h2o-3.28.0.1.zip
mv /opt/h2o-3.28.0.1 /opt/h2o
rm /opt/h2o-3.28.0.1.zip
chmod -R 755 /opt/h2o && chown -R ubuntu:ubuntu /opt/h2o
