#!/bin/bash

FILE=${DOMINO_WORKING_DIR}/vscode-settings/User/settings.json
VSCODEFILE=${DOMINO_WORKING_DIR}/.vscode/settings.json

##turn off auto updating a VSCode extensions and set default python interpreter
#Update user setting file if it does exist
if [ -f "$FILE" ]; then
jq --argjson value false --arg PYTHONINTERPRETERPATH "$(which python)" '. + {"extensions.autoUpdate": $value,"python.pythonPath": $PYTHONINTERPRETERPATH}' $FILE > temp-settings.json
mv temp-settings.json $FILE
rm -rf temp-settings.json
fi

#Add user settings file if it doesn't exist
if [ ! -f "$FILE" ]; then
mkdir -p ${DOMINO_WORKING_DIR}/vscode-settings/User/
printf "{\n\t\"extensions.autoUpdate\":false,\n\t\"python.pythonPath\": \"$(which python)\"\n}\n" > ${DOMINO_WORKING_DIR}/vscode-settings/User/settings.json
fi

#Add .vscode settings file if it doesn't exist
if [ ! -f "$VSCODEFILE" ]; then
mkdir -p ${DOMINO_WORKING_DIR}/.vscode
printf "{\n\t\"extensions.autoUpdate\":false,\n\t\"python.pythonPath\": \"$(which python)\"\n}\n" > $VSCODEFILE
fi

#Update .vscode settings file if it doesn't exist
if [ -f "$VSCODEFILE" ]; then
jq --argjson value false --arg PYTHONINTERPRETERPATH "$(which python)" '. + {"extensions.autoUpdate": $value,"python.pythonPath": $PYTHONINTERPRETERPATH}' $VSCODEFILE > temp-settings.json
mv temp-settings.json $VSCODEFILE
rm -rf temp-settings.json
fi

code-server ${DOMINO_WORKING_DIR} --user-data-dir ${DOMINO_WORKING_DIR}/vscode-settings --auth none --bind-addr 0.0.0.0:8888 --extensions-dir ${HOME}/.local/share/code-server/extensions --disable-telemetry
